### ISSUE TITLE
Running Calculations on a Pal Already Bred Only Shows the Pal You've Bred

### ISSUE THREAD

**Issue by RevanFan1** [tylercamp/palcalc#44] opened 2024-07-17 23:51 UTC
When you have successfully bred a pal with all the traits you want, if you run the calculation again, it will only give you one option, which is a 0 step path just showing the one you've just bred. It should be able to still show you the other paths to get to that pal.

Using version 1.50 of PalCalc.

My settings are in the photo. My save file in the link.

https://www.mediafire.com/file/blb7h8ore69uzp7/CA8B02B1421DE8698FDC0085714D44CC.7z/file

![PalCalc Settings](https://github.com/user-attachments/assets/21284c39-b0c0-42a8-a1f7-14642c1aa9fa)

**Comment by tylercamp** [comment] 2024-07-18 00:52
Thanks for the save file, I can repro with this. Planning to include a fix for next release

Btw you can use "Export Save" to just include the required files (~10.5MB instead of ~250MB with all the backups)

**Comment by tylercamp** [comment] 2024-07-18 01:20
Will be fixed in v1.6.0 with d5a8f280700d83648bc668d5990c4de31a66ffd4

**Comment by tylercamp** [comment] 2024-07-18 13:09
@Fusionette Working now, but try disabling the post-solver filter which reduces the final pal results, `MainWindowViewModel:L351-380`

The original issue I solved with this was from results being found but filtered out after solving, which might be a similar problem to what you're describing

**Comment by tylercamp** [comment] 2024-07-18 22:19
Confirmed locally that disabling `VariedResultsPruning` gives results including parents which are the same pal, but it also drastically increases the working set size (~4m -> ~12m on step 2)

In #22 for including IV inheritance in the calculation, I mentioned exposing the `ResultPruning` options in UI so this could be customized by users.

Since this behavior is specifically relevant for IVs and doesn't affect Pal Calc's current feature scope (so long as IV inheritance probabilities are still poorly defined), I'm going to close this as solved, but discussion can continue in #22 or in a new issue specifically for exposing the pruning behavior in UI

**Closed by tylercamp** 2024-07-18 22:19 UTC
Labels: bug
