### ISSUE TITLE
Suggests Pals that are no longer available

### ISSUE THREAD

**Issue by phiilu** [tylercamp/palcalc#15] opened 2024-05-22 15:55 UTC
Thanks for this awesome tool! 

I noticed that I often get suggestions of Pals that are no longer available. This could be because I have butchered them or condensed them. 

For example here:

![2024-05-22 17_47_56-Pal Calc](https://github.com/tylercamp/palcalc/assets/8149519/9ae96a17-3ba3-4e12-94ed-92ff4c90dd31)

I don't have this Jetdragon anymore, because I condensed it (RIP) and now I need to breed it again.

**Comment by tylercamp** [comment] 2024-05-22 17:12
Strange, do you get any pop ups about reading the save file when you open the app?

**Comment by phiilu** [comment] 2024-05-22 17:22
Yes you mean that one? 

![2024-05-22 19_15_29-Pal Calc](https://github.com/tylercamp/palcalc/assets/8149519/556dd678-f6be-4b1a-8c32-7ab5d3b4fe8a)

Also here the Jetdragon with Clumsy does not exist. Before taking the Screenshot I went back to the menu to force a save and than opened Palcalc and rerun the calculation. 

![Screenshot 2024-05-22 192205](https://github.com/tylercamp/palcalc/assets/8149519/e26912f6-1ac9-41c2-87c6-b58edc34cb2a)

![2024-05-22 19_20_07-Pal](https://github.com/tylercamp/palcalc/assets/8149519/d939af03-4fa1-40ef-a6c8-bd3268746a7e)

I sort the Palbox by Paldex.

**Comment by tylercamp** [comment] 2024-05-22 17:25
Hmm, I suspected that it was referencing a previously-cached version of the save from when you still had that pal, but you only have one entry in your list on the left - was this your first time running Pal Calc? Or did you re-run it later to get this result?

Some possible causes for the root issue:

- Steam save not synced locally
- A bug in the logic for detecting when the cached save data is outdated
- A bug in the logic for detecting the type of each pal container

**Comment by tylercamp** [comment] 2024-05-22 17:27
Ah whoops, didn't notice your latest comment

Yes, that's the notification I'm referring to. If that's popping up then I suspect there's an issue with pal container type detection, can you attach the Level.sav file from your save?

**Comment by phiilu** [comment] 2024-05-22 17:33
Sure, I had to zip it. Thanks for looking into it!

[Level.zip](https://github.com/tylercamp/palcalc/files/15406773/Level.zip)

**Comment by tylercamp** [comment] 2024-05-22 18:49
Forgot to mention, could you also provide the files in the "Players" folder next to the Level.sav

**Comment by phiilu** [comment] 2024-05-22 19:57
Here you go

[Players.zip](https://github.com/tylercamp/palcalc/files/15408129/Players.zip)

**Comment by tylercamp** [comment] 2024-05-25 13:24
Seems like the issue is due to an incorrect assumption about how butchered pals are handled. After butchering some pals in my save file I noticed the pal instance data still associates them with my party container, but when looking at the data for that container, the list does not contain the butchered pal. Instead there are now multiple pals which reference the same slot.

The original issues #11 and #12 led to the assumption that butchered/etc. pals would be moved to some untracked container, and those pals should be ignored. Instead we should just be looking at the list of pal containers and the pals within them, and only include pals from those containers.

I'll push a fix soon

**Comment by tylercamp** [comment] 2024-05-25 13:41
@phiilu With the new logic I'm seeing 475 "living" pals out of 2407 total pals in your save file, does that sound right? Where missing pals could be butchered/condensed

**Comment by tylercamp** [comment] 2024-05-25 13:50
Just loaded up your save to confirm (nice base btw) and don't see any jetragon with `Runner`

The displayed locations for the Jetragons are also correct 👍

**Comment by phiilu** [comment] 2024-05-25 14:02
@tylercamp yes that sounds reasonable and yes I think at that save point I did not have a `Runner` Jetdragon. 

Awesome that you figured it out and really appreciate your work you did with Palcalc!

**Comment by tylercamp** [comment] 2024-05-25 14:04
@phiilu Thanks! This should be fixed in [v1.4.1](https://github.com/tylercamp/palcalc/releases/tag/v1.4.1), please close this issue once you've confirmed

**Comment by phiilu** [comment] 2024-05-25 16:47
I tried it out and for now I did not find any problems 🎉

**Closed** 2024-06-08 16:02 UTC
Labels: bug
