### ISSUE TITLE
Pal save not yet cached and error occurred when loading save file

### ISSUE THREAD

**Issue by vabe1177** [tylercamp/palcalc#72] opened 2024-12-24 01:11 UTC
I apologize if this has already been discussed and i missed it but whenever I launch palcalc it states that the save may not have been cached yet and an error occurs when loading a save file. I don't know if it is an error on my end or if it may just be incompatible with the new update. 

[log20241223.txt](https://github.com/user-attachments/files/18234639/log20241223.txt)

**Comment by tylercamp** [comment] 2024-12-24 03:37
@vabe1177 Interesting that seems new

Could you provide the contents of this folder mentioned in the logs:

C:\Users\Owner\AppData\Local\Packages\PocketpairInc.Palworld_ad4psfrxyesvt\SystemAppData\wgs\000901F472D0930D_0000000000000000000000006B210A9C\ADFDDC4822AF494688B5AEEC941A7396\

(Preferably the whole wgs folder, but it might be too big)

**Comment by vabe1177** [comment] 2024-12-24 03:57
[Uploading wgs - Copy.zip…]()

Here you go

**Comment by pedrohpaes** [comment] 2024-12-24 05:35
I'm having the same issue.

[log20241223.txt](https://github.com/user-attachments/files/18236171/log20241223.txt)

**Comment by tylercamp** [comment] 2024-12-24 15:25
Looks like it's related to this: https://github.com/cheahjs/palworld-save-tools/issues/192

The errors here occur when reading guild info, though on my Steam save there's no error and I just get guilds without any players. Still looking into a fix

**Comment by tylercamp** [comment] 2024-12-24 15:29
I've confirmed that the change mentioned in the previous link fixes the issue, will be included in 1.10.1

**Comment by tylercamp** [comment] 2024-12-24 21:33
Fixed with v1.10.1

**Closed by tylercamp** 2024-12-24 21:33 UTC
Labels: bug, pending release
