### ISSUE TITLE
   zh-Hans

### ISSUE THREAD

**Issue by yhpopcom** [tylercamp/palcalc#69] opened 2024-12-15 13:24 UTC
I translated it to zh but when I was debugging, pal was still in English, including the passive skills 
I used a very stupid method to directly replace Chinese with "en" in db.json
I don't know much about code

我把它翻译成了zh但是我在调​​试的时候pal还是英文的，包括被动技能
我用很笨的方法把db.json "en" 直接替换为中文
我不是很懂代码

**Comment by tylercamp** [comment] 2024-12-15 13:44
The zh-Hans translations for pals and passive skills should already exist, BUT I can see that changing the language to zh-Hans doesn't change pal names.

It works for other languages, so there must be a bug involving Chinese specifically. I'll look into this and plan to fix in v1.10.0

**Comment by tylercamp** [comment] 2024-12-15 13:52
@yhpopcom I've just pushed a fix to the `main` branch, it should work now

The problem was caused by v1.9.0 and the fix will be included in v1.10.0

**Comment by tylercamp** [comment] 2024-12-19 02:28
Reopening for some updates that were  missed

**Comment by tylercamp** [comment] 2024-12-24 21:32
Updated in v1.10.1

**Closed by tylercamp** 2024-12-24 21:32 UTC
Labels: bug, pending release
