### ISSUE TITLE
Program crashing upon startup

### ISSUE THREAD

**Issue by Banaface** [tylercamp/palcalc#11] opened 2024-05-07 23:32 UTC
[CRASHLOG.zip](https://github.com/tylercamp/palcalc/files/15242126/CRASHLOG.zip)
Few details to give. Every time I open the calculator, it gives me an error loading the save (log attached). It is most likely because I am playing with a mod that increases the number of slots to 1920. Assuming this is the issue and im not being dense, then it seems like it would be a worthwhile addition, both to allow for use with the mod and future-proofing in case the palbox gets expanded in a future update. Looks like a great tool tho and I cant wait to use it!

**Comment by Banaface** [comment] 2024-05-07 23:39
Just double-checked by making a new save, no issues on the new one. (Although I had to delete the old files because the program would auto select my other save, so maybe adding a way to choose saves before one is picked would also be a good idea)

**Comment by tylercamp** [comment] 2024-05-08 14:04
Thanks for opening this issue and providing the CRASHLOG file, I'm able to reproduce with the save file it contains, will take a closer look later today

Will also take a look at adding a "no save selected" state to use when there's a problem loading a save

**Comment by tylercamp** [comment] 2024-05-08 19:32
@Banaface The issue is caused by pals being in a container (e.g. player party, palbox, base) which can't be found inside the `Level.sav` file. It looks like this container has 40 slots, and while your mod increases palbox slots to 1920, I'm not aware of any built-in pal containers with a limit of 40 pals. I see a bunch of other containers with 20 slots, i.e. bases, so I don't think it's a base.

It also looks like these pals are all owned by you ("Banaface"). Do you know where you might have 40 pals stored together?

**Comment by tylercamp** [comment] 2024-05-09 12:24
@Banaface This should be fixed with [v1.0.2](https://github.com/tylercamp/palcalc/releases/tag/v1.0.2), please confirm

**Comment by Banaface** [comment] 2024-05-09 16:00
Sorry, I was going to check all my containers, but power went out as soon as I got home. I'll test the new update as soon as they restore power. Thanks for responding so quickly tho!

**Comment by tylercamp** [comment] 2024-05-09 17:02
Based on #12 it seems like this may be caused by butchered pals, have you done that in your save?

**Closed** 2024-05-09 18:40 UTC
